### ISSUE TITLE
Class property bug with multiple instances of contenteditor

### ISSUE THREAD

**Issue by jonathan-hc** [Samuell1/contenteditor-plugin#101] opened 2020-07-29 18:27 UTC
**Issue:** If there are multiple contenteditor instances in a template and one of them uses the class property, the value for the property gets applied to all the instances that follow it in the template.
**Workaround:** We need to reset the class property by adding an empty class property to all the following instances of content builder
**ContentEditor Version:** 1.3.1
**OctoberCMS Build:** 467

**Comment by samuelpatro** [comment] 2020-07-29 19:44
Duplicate of #81

**Closed as completed by samuelpatro** 2020-07-29 19:44 UTC
